### ISSUE TITLE
check_vies is not working anymore

### ISSUE THREAD

**Issue by sebest** [arthurdejong/python-stdnum#31] opened 2015-11-25 20:11 UTC
i'm using the following code:
```
from stdnum.eu import vat
print vat.check_vies('FR 75483487112')
```

and get the following error:
```
raceback (most recent call last):
  File "t.py", line 2, in <module>
    print vat.check_vies('FR 75483487112')
  File "/Users/sebest/.virtualenvs/pxlapi/lib/python2.7/site-packages/stdnum/eu/vat.py", line 144, in check_vies
    return _get_client().checkVat(number[:2], number[2:])
  File "/Users/sebest/.virtualenvs/pxlapi/lib/python2.7/site-packages/stdnum/eu/vat.py", line 128, in _get_client
    _vies_client = Client(vies_wsdl, proxy=getproxies()).service
  File "/Users/sebest/.virtualenvs/pxlapi/lib/python2.7/site-packages/suds/client.py", line 112, in __init__
    self.wsdl = reader.open(url)
  File "/Users/sebest/.virtualenvs/pxlapi/lib/python2.7/site-packages/suds/reader.py", line 152, in open
    d = self.fn(url, self.options)
  File "/Users/sebest/.virtualenvs/pxlapi/lib/python2.7/site-packages/suds/wsdl.py", line 136, in __init__
    d = reader.open(url)
  File "/Users/sebest/.virtualenvs/pxlapi/lib/python2.7/site-packages/suds/reader.py", line 79, in open
    d = self.download(url)
  File "/Users/sebest/.virtualenvs/pxlapi/lib/python2.7/site-packages/suds/reader.py", line 101, in download
    return sax.parse(string=content)
  File "/Users/sebest/.virtualenvs/pxlapi/lib/python2.7/site-packages/suds/sax/parser.py", line 136, in parse
    sax.parse(source)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/sax/expatreader.py", line 110, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/sax/expatreader.py", line 217, in feed
    self._err_handler.fatalError(exc)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/sax/handler.py", line 38, in fatalError
    raise exception
xml.sax._exceptions.SAXParseException: <unknown>:21:6: mismatched tag
```

**Comment by arthurdejong** [comment] 2015-11-30 18:43
Hi Sebastien,

I cannot reproduce this at this time (neither the Git version or the 1.2 version). It could be that VIES was down at the time. python-stdnum does not do any error handling in this case and any exceptions of the underlying SOAP library are not caught.

**Comment by arthurdejong** [comment] 2016-07-26 21:28
Closing this issue now. Feel free to re-open or raise a new issue if it fails again.

**Closed by arthurdejong** 2016-07-26 21:28 UTC
